export const CareersList = [
  { value: "Accountant", label: "Accountant" },
  { value: "Acrobat", label: "Acrobat" },
  { value: "Actor/Actress", label: "Actor/Actress" },
  { value: "Actuary", label: "Actuary" },
  { value: "Acupuncturist", label: "Acupuncturist" },
  { value: "Administrator", label: "Administrator" },
  { value: "Aerospace engineer", label: "Aerospace engineer" },
  { value: "Air traffic controller", label: "Air traffic controller" },
  { value: "Alchemist", label: "Alchemist" },
  { value: "Alderman", label: "Alderman" },
  { value: "Ambassador", label: "Ambassador" },
  { value: "Analyst", label: "Analyst" },
  { value: "Anesthetist", label: "Anesthetist" },
  { value: "Anesthesiologist", label: "Anesthesiologist" },
  { value: "Anchorman", label: "Anchorman" },
  { value: "Animator", label: "Animator" },
  { value: "Animal Trainer", label: "Animal Trainer" },
  { value: "Announcer", label: "Announcer" },
  { value: "Antique dealer", label: "Antique dealer" },
  { value: "Arborist", label: "Arborist" },
  { value: "Archaeologist", label: "Archaeologist" },
  { value: "Archbishop", label: "Archbishop" },
  { value: "Architect", label: "Architect" },
  { value: "Archivist", label: "Archivist" },
  { value: "Art dealer", label: "Art dealer" },
  { value: "Art director", label: "Art director" },
  { value: "Artist", label: "Artist" },
  { value: "Assayer", label: "Assayer" },
  { value: "Assessor", label: "Assessor" },
  { value: "Assistant", label: "Assistant" },
  { value: "Astrologer", label: "Astrologer" },
  { value: "Astronaut", label: "Astronaut" },
  { value: "Astronomer", label: "Astronomer" },
  { value: "Astrophysicist", label: "Astrophysicist" },
  { value: "Athlete", label: "Athlete" },
  { value: "Athletic trainer", label: "Athletic trainer" },
  { value: "Attorney", label: "Attorney" },
  { value: "Auctioneer", label: "Auctioneer" },
  { value: "Author", label: "Author" },
  { value: "Automobile racer", label: "Automobile racer" },
  { value: "Automotive designer", label: "Automotive designer" },
  { value: "Audiologist", label: "Audiologist" },
  { value: "Auditor", label: "Auditor" },
  { value: "Audio Analyser", label: "Audio Analyser" },
  { value: "Babysitter", label: "Babysitter" },
  { value: "Bacteriologist", label: "Bacteriologist" },
  { value: "Bailiff", label: "Bailiff" },
  { value: "Baker", label: "Baker" },
  { value: "Balloonist", label: "Balloonist" },
  { value: "Bank teller", label: "Bank teller" },
  { value: "Banker", label: "Banker" },
  { value: "Bar keeper", label: "Bar keeper" },
  { value: "Barber", label: "Barber" },
  { value: "Bargeman", label: "Bargeman" },
  { value: "Barista", label: "Barista" },
  { value: "Barman", label: "Barman" },
  { value: "Barrister", label: "Barrister" },
  { value: "Bartender", label: "Bartender" },
  { value: "Bassoonist", label: "Bassoonist" },
  { value: "Batman", label: "Batman" },
  { value: "Beautician", label: "Beautician" },
  { value: "Beauty specialist", label: "Beauty specialist" },
  { value: "Beauty therapist", label: "Beauty therapist" },
  { value: "Beekeeper", label: "Beekeeper" },
  { value: "Bellhop", label: "Bellhop" },
  { value: "Biographer", label: "Biographer" },
  { value: "Biologist", label: "Biologist" },
  { value: "Bishop", label: "Bishop" },
  { value: "Blacksmith", label: "Blacksmith" },
  { value: "Boatman", label: "Boatman" },
  { value: "Bodyguard", label: "Bodyguard" },
  { value: "Boilermaker", label: "Boilermaker" },
  { value: "Bookbinder", label: "Bookbinder" },
  { value: "Bookkeeper", label: "Bookkeeper" },
  { value: "Bookseller", label: "Bookseller" },
  {
    value: "Border patrol police officer",
    label: "Border patrol police officer",
  },
  { value: "Bounty hunter", label: "Bounty hunter" },
  { value: "Boxer", label: "Boxer" },
  { value: "Blacksmith", label: "Blacksmith" },
  { value: "Brain surgeon", label: "Brain surgeon" },
  { value: "Brewer", label: "Brewer" },
  { value: "Bricklayer", label: "Bricklayer" },
  { value: "Broker", label: "Broker" },
  { value: "Builder", label: "Builder" },
  { value: "Bureaucrat", label: "Bureaucrat" },
  { value: "Butcher", label: "Butcher" },
  { value: "Butler", label: "Butler" },
  { value: "Heading text", label: "Heading text" },
  { value: "Cab driver", label: "Cab driver" },
  { value: "Cabinetmaker", label: "Cabinetmaker" },
  { value: "Caddy", label: "Caddy" },
  { value: "Calligrapher", label: "Calligrapher" },
  { value: "Cameraman", label: "Cameraman" },
  { value: "Captain", label: "Captain" },
  { value: "Cardinal", label: "Cardinal" },
  { value: "Cardiologist", label: "Cardiologist" },
  { value: "Carpenter", label: "Carpenter" },
  { value: "Cartoonist", label: "Cartoonist" },
  { value: "Cartographer", label: "Cartographer" },
  { value: "Cashier", label: "Cashier" },
  { value: "Cellist", label: "Cellist" },
  { value: "Chancellor", label: "Chancellor" },
  { value: "Chaplain", label: "Chaplain" },
  { value: "Chauffeur", label: "Chauffeur" },
  { value: "Chess player", label: "Chess player" },
  { value: "Cheesemaker", label: "Cheesemaker" },
  { value: "Chef", label: "Chef" },
  { value: "Chemist", label: "Chemist" },
  { value: "Chief Compliance Officer", label: "Chief Compliance Officer" },
  { value: "Chief engineer", label: "Chief engineer" },
  { value: "Chief Executive Officer", label: "Chief Executive Officer" },
  { value: "Chief Financial Officer", label: "Chief Financial Officer" },
  { value: "Chief Information Officer", label: "Chief Information Officer" },
  { value: "Chief Technology Officer", label: "Chief Technology Officer" },
  { value: "Chief Privacy Officer", label: "Chief Privacy Officer" },
  { value: "Chief of Police", label: "Chief of Police" },
  { value: "Chimney sweep", label: "Chimney sweep" },
  { value: "Chiropodist", label: "Chiropodist" },
  { value: "Chiropractor", label: "Chiropractor" },
  { value: "Choreographer", label: "Choreographer" },
  { value: "Cinematographer", label: "Cinematographer" },
  { value: "Civil servant", label: "Civil servant" },
  { value: "Civil engineer", label: "Civil engineer" },
  { value: "Clarinetist", label: "Clarinetist" },
  { value: "Cleaner", label: "Cleaner" },
  { value: "Clergymen", label: "Clergymen" },
  { value: "Clerk", label: "Clerk" },
  { value: "Climatologist", label: "Climatologist" },
  { value: "Clockmaker", label: "Clockmaker" },
  { value: "Clown", label: "Clown" },
  { value: "Coach", label: "Coach" },
  { value: "Coachman", label: "Coachman" },
  { value: "Coast guard", label: "Coast guard" },
  { value: "Cobbler", label: "Cobbler" },
  { value: "Columnist", label: "Columnist" },
  { value: "Comedian", label: "Comedian" },
  { value: "Company secretary", label: "Company secretary" },
  { value: "Compasssmith", label: "Compasssmith" },
  { value: "Composer", label: "Composer" },
  { value: "Computer programmer", label: "Computer programmer" },
  { value: "Conductor (music)", label: "Conductor (music)" },
  { value: "Conductor (transportation)", label: "Conductor (transportation)" },
  { value: "Confectioner", label: "Confectioner" },
  { value: "Conferencier", label: "Conferencier" },
  { value: "Constable", label: "Constable" },
  { value: "Cooper", label: "Cooper" },
  { value: "Construction engineering", label: "Construction engineering" },
  { value: "Construction foreman", label: "Construction foreman" },
  { value: "Construction worker", label: "Construction worker" },
  { value: "Consul", label: "Consul" },
  { value: "Consultant", label: "Consultant" },
  { value: "Controller", label: "Controller" },
  { value: "Cosmetologist", label: "Cosmetologist" },
  { value: "Contractor, general", label: "Contractor, general" },
  { value: "Cook", label: "Cook" },
  { value: "Copywriter", label: "Copywriter" },
  { value: "Coroner", label: "Coroner" },
  { value: "Corrections officer", label: "Corrections officer" },
  { value: "Corrector", label: "Corrector" },
  { value: "Correspondent", label: "Correspondent" },
  { value: "Cosmetologist", label: "Cosmetologist" },
  { value: "Cosmonaut", label: "Cosmonaut" },
  { value: "Costume designer", label: "Costume designer" },
  { value: "Courier", label: "Courier" },
  { value: "Court jester", label: "Court jester" },
  { value: "Cowboy", label: "Cowboy" },
  { value: "Crafter", label: "Crafter" },
  { value: "Crammer", label: "Crammer" },
  { value: "Cryptographer", label: "Cryptographer" },
  { value: "Cryptozoologist", label: "Cryptozoologist" },
  { value: "Curator", label: "Curator" },
  { value: "Currier", label: "Currier" },
  { value: "Custodian", label: "Custodian" },
  {
    value: "Customer service representative",
    label: "Customer service representative",
  },
  { value: "Customs officer", label: "Customs officer" },
  { value: "Cyclist", label: "Cyclist" },
  { value: "Dancer", label: "Dancer" },
  { value: "Dealer", label: "Dealer" },
  { value: "Delivery man", label: "Delivery man" },
  { value: "Dental hygienist", label: "Dental hygienist" },
  { value: "Dentist", label: "Dentist" },
  { value: "Deputy (Law Enforcement)", label: "Deputy (Law Enforcement)" },
  { value: "Dermatologist", label: "Dermatologist" },
  { value: "Demolitionist", label: "Demolitionist" },
  { value: "Designer", label: "Designer" },
  { value: "Detective", label: "Detective" },
  { value: "Dietician", label: "Dietician" },
  { value: "Dictator", label: "Dictator" },
  { value: "Diplomat", label: "Diplomat" },
  { value: "Disc jockey", label: "Disc jockey" },
  { value: "Dispatcher", label: "Dispatcher" },
  { value: "Diver", label: "Diver" },
  { value: "Dock labourer", label: "Dock labourer" },
  { value: "Doctor", label: "Doctor" },
  { value: "Documentalist", label: "Documentalist" },
  { value: "Dog walker", label: "Dog walker" },
  { value: "Doorman", label: "Doorman" },
  { value: "Dramatist", label: "Dramatist" },
  { value: "Dressmaker", label: "Dressmaker" },
  { value: "Dressman", label: "Dressman" },
  { value: "Driver", label: "Driver" },
  { value: "Drug dealer", label: "Drug dealer" },
  { value: "Drummer", label: "Drummer" },
  { value: "DJ", label: "DJ" },
  { value: "Ecologist", label: "Ecologist" },
  { value: "Editor", label: "Editor" },
  { value: "Educationalist", label: "Educationalist" },
  { value: "Electrical engineer", label: "Electrical engineer" },
  { value: "Electrician", label: "Electrician" },
  { value: "Escort", label: "Escort" },
  { value: "Embalmer", label: "Embalmer" },
  { value: "Engine-driver", label: "Engine-driver" },
  { value: "Engine fitter", label: "Engine fitter" },
  { value: "Engineer", label: "Engineer" },
  { value: "Entertainer", label: "Entertainer" },
  { value: "Entrepreneur", label: "Entrepreneur" },
  { value: "Environmental scientist", label: "Environmental scientist" },
  { value: "Estate agent", label: "Estate agent" },
  { value: "Ethnologist", label: "Ethnologist" },
  { value: "Ethologist", label: "Ethologist" },
  { value: "Etymologist", label: "Etymologist" },
  { value: "Evangelist", label: "Evangelist" },
  { value: "Examiner", label: "Examiner" },
  { value: "Executive", label: "Executive" },
  { value: "Executor", label: "Executor" },
  { value: "Exotic dancer", label: "Exotic dancer" },
  { value: "Explorer", label: "Explorer" },
  { value: "Executioner", label: "Executioner" },
  { value: "Factory worker", label: "Factory worker" },
  { value: "Falconer", label: "Falconer" },
  { value: "Farmer", label: "Farmer" },
  { value: "Farrier", label: "Farrier" },
  { value: "Fashion designer", label: "Fashion designer" },
  { value: "Ferryman", label: "Ferryman" },
  { value: "Film critic", label: "Film critic" },
  { value: "Film director", label: "Film director" },
  { value: "Film producer", label: "Film producer" },
  { value: "Financial adviser", label: "Financial adviser" },
  { value: "Fire marshal", label: "Fire marshal" },
  { value: "Fire Safety Officer", label: "Fire Safety Officer" },
  { value: "Firefighter", label: "Firefighter" },
  { value: "First mate", label: "First mate" },
  { value: "Fisherman", label: "Fisherman" },
  { value: "Fishmonger", label: "Fishmonger" },
  { value: "Fishwife", label: "Fishwife" },
  { value: "Fitter", label: "Fitter" },
  { value: "Flautist", label: "Flautist" },
  { value: "Flavorist", label: "Flavorist" },
  { value: "Fletcher", label: "Fletcher" },
  { value: "Flight attendant", label: "Flight attendant" },
  { value: "Flight instructor", label: "Flight instructor" },
  { value: "Flight technician", label: "Flight technician" },
  { value: "Flight engineer", label: "Flight engineer" },
  { value: "Floor manager", label: "Floor manager" },
  { value: "Florist", label: "Florist" },
  { value: "Flutist", label: "Flutist" },
  { value: "Food critic", label: "Food critic" },
  { value: "Footballer", label: "Footballer" },
  { value: "Footman", label: "Footman" },
  { value: "Forester", label: "Forester" },
  { value: "Fortune teller", label: "Fortune teller" },
  { value: "Fowler", label: "Fowler" },
  { value: "Freedom fighter", label: "Freedom fighter" },
  { value: "Funeral director", label: "Funeral director" },
  { value: "Game designer", label: "Game designer" },
  { value: "Game show host", label: "Game show host" },
  { value: "Game warden", label: "Game warden" },
  { value: "Gamekeeper", label: "Gamekeeper" },
  { value: "Gangster", label: "Gangster" },
  { value: "Garbage collector", label: "Garbage collector" },
  { value: "Gardener", label: "Gardener" },
  { value: "Gate-keeper", label: "Gate-keeper" },
  { value: "Gemcutter", label: "Gemcutter" },
  { value: "Genealogist", label: "Genealogist" },
  { value: "General", label: "General" },
  { value: "Geographer", label: "Geographer" },
  { value: "Geologist", label: "Geologist" },
  { value: "Geometrician", label: "Geometrician" },
  { value: "Geophysicist", label: "Geophysicist" },
  { value: "Gigolo", label: "Gigolo" },
  { value: "Gladiator", label: "Gladiator" },
  { value: "Goldsmith", label: "Goldsmith" },
  { value: "Gondolier", label: "Gondolier" },
  { value: "Gofer", label: "Gofer" },
  { value: "Governess", label: "Governess" },
  { value: "Government agent", label: "Government agent" },
  { value: "Governor", label: "Governor" },
  { value: "Grammarian", label: "Grammarian" },
  { value: "Graphic artist", label: "Graphic artist" },
  { value: "Graphic designer", label: "Graphic designer" },
  { value: "Gravedigger", label: "Gravedigger" },
  { value: "Greengrocer", label: "Greengrocer" },
  { value: "Grocer", label: "Grocer" },
  { value: "Guard", label: "Guard" },
  { value: "Guide", label: "Guide" },
  { value: "Guitarist", label: "Guitarist" },
  { value: "Gunsmith", label: "Gunsmith" },
  { value: "Hairdresser", label: "Hairdresser" },
  { value: "Hairstylist", label: "Hairstylist" },
  { value: "Handyman", label: "Handyman" },
  { value: "Harbourmaster", label: "Harbourmaster" },
  { value: "Harpist", label: "Harpist" },
  { value: "Hatter", label: "Hatter" },
  { value: "Headmaster", label: "Headmaster" },
  { value: "Headmistress", label: "Headmistress" },
  { value: "Health inspector", label: "Health inspector" },
  { value: "Herder", label: "Herder" },
  { value: "Historian", label: "Historian" },
  { value: "Hitman", label: "Hitman" },
  { value: "Homeopath", label: "Homeopath" },
  { value: "Hornist", label: "Hornist" },
  { value: "Host", label: "Host" },
  { value: "Hostess", label: "Hostess" },
  { value: "Hotel manager", label: "Hotel manager" },
  { value: "Hotelier", label: "Hotelier" },
  { value: "House painter", label: "House painter" },
  { value: "Housekeeper", label: "Housekeeper" },
  { value: "Housewife", label: "Housewife" },
  { value: "Homeowner", label: "Homeowner" },
  { value: "Hunter", label: "Hunter" },
  { value: "Hydraulic engineer", label: "Hydraulic engineer" },
  { value: "Ice cream man", label: "Ice cream man" },
  { value: "Illuminator", label: "Illuminator" },
  { value: "Illusionist", label: "Illusionist" },
  { value: "Illustrator", label: "Illustrator" },
  { value: "Image consultant", label: "Image consultant" },
  { value: "Imam", label: "Imam" },
  { value: "Impersonator", label: "Impersonator" },
  { value: "Importer", label: "Importer" },
  { value: "Industrial engineer", label: "Industrial engineer" },
  { value: "Industrialist", label: "Industrialist" },
  { value: "Information technologist", label: "Information technologist" },
  { value: "Information broker", label: "Information broker" },
  { value: "Inker", label: "Inker" },
  { value: "Innkeeper", label: "Innkeeper" },
  { value: "Instructor", label: "Instructor" },
  { value: "Insurer", label: "Insurer" },
  { value: "Intelligence officer", label: "Intelligence officer" },
  { value: "Intercity bus driver", label: "Intercity bus driver" },
  { value: "Interior designer", label: "Interior designer" },
  { value: "Internist", label: "Internist" },
  { value: "Interpreter", label: "Interpreter" },
  { value: "Interrogator", label: "Interrogator" },
  { value: "Inventor", label: "Inventor" },
  { value: "Investment banker", label: "Investment banker" },
  { value: "Investment broker", label: "Investment broker" },
  { value: "Ironmonger", label: "Ironmonger" },
  { value: "Ironmaster", label: "Ironmaster" },
  { value: "Ironworker", label: "Ironworker" },
  { value: "Jailer", label: "Jailer" },
  { value: "Janitor", label: "Janitor" },
  { value: "Jeweller", label: "Jeweller" },
  { value: "Jockey", label: "Jockey" },
  { value: "Joggler", label: "Joggler" },
  { value: "Joiner", label: "Joiner" },
  { value: "Joker", label: "Joker" },
  { value: "Journalist", label: "Journalist" },
  { value: "Judge", label: "Judge" },
  { value: "Juggler", label: "Juggler" },
  { value: "Jurist", label: "Jurist" },
  { value: "Karate master", label: "Karate master" },
  { value: "Kickboxer", label: "Kickboxer" },
  { value: "Kindergarten teacher", label: "Kindergarten teacher" },
  { value: "Kinesiologist", label: "Kinesiologist" },
  { value: "King", label: "King" },
  { value: "Laboratory worker", label: "Laboratory worker" },
  { value: "Laborer", label: "Laborer" },
  { value: "Lady-in-waiting", label: "Lady-in-waiting" },
  { value: "Landlord (also Landlady)", label: "Landlord (also Landlady)" },
  { value: "Laundress (also Lavendar)", label: "Laundress (also Lavendar)" },
  { value: "Law enforcement agent", label: "Law enforcement agent" },
  { value: "Lawyer", label: "Lawyer" },
  { value: "Leadworker", label: "Leadworker" },
  { value: "Leatherer", label: "Leatherer" },
  { value: "Leather worker", label: "Leather worker" },
  { value: "Lecturer", label: "Lecturer" },
  { value: "Legislator", label: "Legislator" },
  {
    value: "Level designer (also Mapper)",
    label: "Level designer (also Mapper)",
  },
  { value: "Librarian", label: "Librarian" },
  { value: "Librarianship", label: "Librarianship" },
  { value: "Librettist", label: "Librettist" },
  { value: "Lieutenant", label: "Lieutenant" },
  { value: "Lifeguard", label: "Lifeguard" },
  { value: "Lighthouse keeper", label: "Lighthouse keeper" },
  { value: "Lighting technician", label: "Lighting technician" },
  { value: "Lineman", label: "Lineman" },
  { value: "Linguist", label: "Linguist" },
  { value: "Loan officer", label: "Loan officer" },
  { value: "Lobbyist", label: "Lobbyist" },
  { value: "Locksmith", label: "Locksmith" },
  { value: "Logistician", label: "Logistician" },
  { value: "Lumberjack", label: "Lumberjack" },
  { value: "Lyricist", label: "Lyricist" },
  { value: "Magistrate", label: "Magistrate" },
  { value: "Magician", label: "Magician" },
  { value: "Magnate", label: "Magnate" },
  { value: "Maid", label: "Maid" },
  { value: "Mailman or Mail carrier", label: "Mailman or Mail carrier" },
  { value: "Make-up artist", label: "Make-up artist" },
  { value: "Management consultant", label: "Management consultant" },
  { value: "Manager", label: "Manager" },
  { value: "Manicurist", label: "Manicurist" },
  { value: "Manservant", label: "Manservant" },
  { value: "Manual therapist", label: "Manual therapist" },
  { value: "Manufacturer", label: "Manufacturer" },
  { value: "Marine", label: "Marine" },
  { value: "Marine biologist", label: "Marine biologist" },
  { value: "Market gardener", label: "Market gardener" },
  { value: "Marketing manager", label: "Marketing manager" },
  { value: "Marksman", label: "Marksman" },
  { value: "Marshal", label: "Marshal" },
  { value: "Martial artist", label: "Martial artist" },
  { value: "Mason", label: "Mason" },
  {
    value: "Master of Business Administration",
    label: "Master of Business Administration",
  },
  { value: "Master of ceremony", label: "Master of ceremony" },
  {
    value: "Massage therapist (also masseuse/masseur)",
    label: "Massage therapist (also masseuse/masseur)",
  },
  { value: "Matador", label: "Matador" },
  { value: "Mathematician", label: "Mathematician" },
  { value: "Matron", label: "Matron" },
  { value: "Mayor", label: "Mayor" },
  { value: "Mechanic", label: "Mechanic" },
  { value: "Mechanical engineer", label: "Mechanical engineer" },
  { value: "Mechanician", label: "Mechanician" },
  { value: "Mediator", label: "Mediator" },
  { value: "Medic", label: "Medic" },
  { value: "Medical biller", label: "Medical biller" },
  {
    value: "Medical laboratory scientist",
    label: "Medical laboratory scientist",
  },
  { value: "Medical transcriptionist", label: "Medical transcriptionist" },
  { value: "Mercer", label: "Mercer" },
  { value: "Merchant", label: "Merchant" },
  { value: "Mesmerist", label: "Mesmerist" },
  { value: "Messenger", label: "Messenger" },
  { value: "Meteorologist", label: "Meteorologist" },
  { value: "Mid-wife", label: "Mid-wife" },
  { value: "Milkman (also Milkmaid)", label: "Milkman (also Milkmaid)" },
  { value: "Miller", label: "Miller" },
  { value: "Miner", label: "Miner" },
  { value: "Minister", label: "Minister" },
  { value: "Missionary", label: "Missionary" },
  { value: "Mobile", label: "Mobile" },
  { value: "Mobster", label: "Mobster" },
  { value: "Model", label: "Model" },
  { value: "Modeller", label: "Modeller" },
  {
    value: "Moldmaker (also Mouldmaker)",
    label: "Moldmaker (also Mouldmaker)",
  },
  { value: "Moneychanger", label: "Moneychanger" },
  { value: "Moneylender", label: "Moneylender" },
  { value: "Monk", label: "Monk" },
  { value: "Moonlighter", label: "Moonlighter" },
  { value: "Mortgage broker", label: "Mortgage broker" },
  { value: "Mountaineer", label: "Mountaineer" },
  { value: "Muralist", label: "Muralist" },
  { value: "Music educator", label: "Music educator" },
  { value: "Music director", label: "Music director" },
  { value: "Musician", label: "Musician" },
  { value: "Nanny (also nursemaid)", label: "Nanny (also nursemaid)" },
  { value: "Navigator", label: "Navigator" },
  { value: "Négociant", label: "Négociant" },
  { value: "Negotiator", label: "Negotiator" },
  { value: "Netmaker", label: "Netmaker" },
  { value: "Neurologist", label: "Neurologist" },
  { value: "Newscaster", label: "Newscaster" },
  { value: "Night auditor", label: "Night auditor" },
  { value: "Nightwatchman", label: "Nightwatchman" },
  { value: "Notary", label: "Notary" },
  { value: "Novelist", label: "Novelist" },
  { value: "Numerologist", label: "Numerologist" },
  { value: "Numismatist", label: "Numismatist" },
  { value: "Nun", label: "Nun" },
  { value: "Nursemaid (also nanny)", label: "Nursemaid (also nanny)" },
  { value: "Nurse", label: "Nurse" },
  { value: "Nutritionist", label: "Nutritionist" },
  { value: "Oboist", label: "Oboist" },
  { value: "Obstetrician", label: "Obstetrician" },
  { value: "Oceanographer", label: "Oceanographer" },
  { value: "Occupational therapist", label: "Occupational therapist" },
  { value: "Ocularist", label: "Ocularist" },
  { value: "Odontologist", label: "Odontologist" },
  { value: "Oenologist", label: "Oenologist" },
  { value: "Oncologist", label: "Oncologist" },
  { value: "Operator", label: "Operator" },
  { value: "Ophthalmologist", label: "Ophthalmologist" },
  { value: "Optician", label: "Optician" },
  { value: "Optometrist", label: "Optometrist" },
  { value: "Oracle", label: "Oracle" },
  { value: "Ordinary seaman", label: "Ordinary seaman" },
  { value: "Organizer", label: "Organizer" },
  { value: "Orthodontist", label: "Orthodontist" },
  { value: "Orthopaedist", label: "Orthopaedist" },
  { value: "Ornithologist", label: "Ornithologist" },
  { value: "Ostler", label: "Ostler" },
  { value: "Otorhinolaryngologist", label: "Otorhinolaryngologist" },
  { value: "Painter", label: "Painter" },
  { value: "Paleontologist", label: "Paleontologist" },
  { value: "Paleoseismologist", label: "Paleoseismologist" },
  { value: "Paralegal", label: "Paralegal" },
  { value: "Paramedic", label: "Paramedic" },
  { value: "Park ranger", label: "Park ranger" },
  { value: "Parole officer", label: "Parole officer" },
  { value: "Party-leader", label: "Party-leader" },
  { value: "Pastor", label: "Pastor" },
  { value: "Patent attorney", label: "Patent attorney" },
  { value: "Patent examiner", label: "Patent examiner" },
  { value: "Pathologist", label: "Pathologist" },
  { value: "Pawnbroker", label: "Pawnbroker" },
  { value: "Peddler", label: "Peddler" },
  { value: "Pediatrician", label: "Pediatrician" },
  { value: "Pedologist (soil)", label: "Pedologist (soil)" },
  { value: "Percussionist", label: "Percussionist" },
  { value: "Perfumer", label: "Perfumer" },
  { value: "Personal trainer", label: "Personal trainer" },
  { value: "Pharmacist", label: "Pharmacist" },
  { value: "Philanthropist", label: "Philanthropist" },
  { value: "Philologist", label: "Philologist" },
  { value: "Philosopher", label: "Philosopher" },
  { value: "Photographer", label: "Photographer" },
  { value: "Photographer assistant", label: "Photographer assistant" },
  { value: "Physical therapist", label: "Physical therapist" },
  { value: "Physician", label: "Physician" },
  { value: "Physician assistant", label: "Physician assistant" },
  { value: "Physicist", label: "Physicist" },
  { value: "Physiognomist", label: "Physiognomist" },
  { value: "Physiologist", label: "Physiologist" },
  { value: "Physiotherapist", label: "Physiotherapist" },
  { value: "Pianist", label: "Pianist" },
  { value: "Piano tuner", label: "Piano tuner" },
  { value: "Pilot", label: "Pilot" },
  { value: "Pilot (shipping)", label: "Pilot (shipping)" },
  { value: "Pimp", label: "Pimp" },
  { value: "Pirate", label: "Pirate" },
  { value: "Plasterer", label: "Plasterer" },
  { value: "Plumber", label: "Plumber" },
  { value: "Podiatrist", label: "Podiatrist" },
  { value: "Poet", label: "Poet" },
  { value: "Poetrist", label: "Poetrist" },
  { value: "Poker player", label: "Poker player" },
  { value: "Poll-taker", label: "Poll-taker" },
  { value: "Police detective", label: "Police detective" },
  { value: "Police inspector", label: "Police inspector" },
  { value: "Police officer", label: "Police officer" },
  { value: "Politician", label: "Politician" },
  { value: "Political scientist", label: "Political scientist" },
  { value: "Pool boy", label: "Pool boy" },
  { value: "Pope", label: "Pope" },
  { value: "Pornographer", label: "Pornographer" },
  { value: "Porn star", label: "Porn star" },
  { value: "Porter", label: "Porter" },
  { value: "Poulterer", label: "Poulterer" },
  { value: "Presenter", label: "Presenter" },
  { value: "President", label: "President" },
  { value: "Press officer", label: "Press officer" },
  { value: "Priest", label: "Priest" },
  { value: "Prime minister", label: "Prime minister" },
  { value: "Prince", label: "Prince" },
  { value: "Princess", label: "Princess" },
  { value: "Principal", label: "Principal" },
  { value: "Printer", label: "Printer" },
  { value: "Prison officer", label: "Prison officer" },
  { value: "Prisoner", label: "Prisoner" },
  { value: "Private detective", label: "Private detective" },
  { value: "Probation officer", label: "Probation officer" },
  { value: "Proctologist", label: "Proctologist" },
  { value: "Producer", label: "Producer" },
  { value: "Product designer", label: "Product designer" },
  { value: "Professor", label: "Professor" },
  { value: "Professional dominant", label: "Professional dominant" },
  { value: "Programmer", label: "Programmer" },
  { value: "Project manager", label: "Project manager" },
  { value: "Proofreader", label: "Proofreader" },
  { value: "Prosecutor", label: "Prosecutor" },
  { value: "Prostitute", label: "Prostitute" },
  { value: "Psychiatrist", label: "Psychiatrist" },
  { value: "Psychodramatist", label: "Psychodramatist" },
  { value: "Psychologist", label: "Psychologist" },
  { value: "Psychotherapist", label: "Psychotherapist" },
  { value: "Public Relations Officer", label: "Public Relations Officer" },
  { value: "Public speaker", label: "Public speaker" },
  { value: "Publicist", label: "Publicist" },
  { value: "Publisher", label: "Publisher" },
  { value: "Puppeteer", label: "Puppeteer" },
  { value: "Queen", label: "Queen" },
  { value: "Queen Consort", label: "Queen Consort" },
  { value: "Queen dowager", label: "Queen dowager" },
  { value: "Queen mother", label: "Queen mother" },
  { value: "Queen Regnant", label: "Queen Regnant" },
  { value: "Quilter", label: "Quilter" },
  { value: "Rabbi", label: "Rabbi" },
  { value: "Radiologist", label: "Radiologist" },
  { value: "Radiographer", label: "Radiographer" },
  { value: "Race driver", label: "Race driver" },
  { value: "Rat-catcher", label: "Rat-catcher" },
  { value: "Real estate broker", label: "Real estate broker" },
  { value: "Real estate investor", label: "Real estate investor" },
  { value: "Real estate developer", label: "Real estate developer" },
  { value: "Receptionist", label: "Receptionist" },
  { value: "Record producer", label: "Record producer" },
  { value: "Referee", label: "Referee" },
  { value: "Refuse collector", label: "Refuse collector" },
  { value: "Registrar", label: "Registrar" },
  { value: "Registered nurse", label: "Registered nurse" },
  { value: "Remedial teacher", label: "Remedial teacher" },
  { value: "Reporter", label: "Reporter" },
  { value: "Researcher", label: "Researcher" },
  { value: "Resource room assisstant", label: "Resource room assisstant" },
  { value: "Respiratory therapist", label: "Respiratory therapist" },
  { value: "Restaurateur", label: "Restaurateur" },
  { value: "Retailer", label: "Retailer" },
  { value: "Revolutionary", label: "Revolutionary" },
  { value: "Rockstar", label: "Rockstar" },
  { value: "Sailmaker", label: "Sailmaker" },
  { value: "Sailor", label: "Sailor" },
  { value: "Sales person", label: "Sales person" },
  { value: "Salesmen", label: "Salesmen" },
  { value: "Sanitation worker", label: "Sanitation worker" },
  { value: "Sarariman", label: "Sarariman" },
  { value: "Saucier", label: "Saucier" },
  { value: "Saxophonist", label: "Saxophonist" },
  { value: "Sawyer", label: "Sawyer" },
  { value: "Scientist", label: "Scientist" },
  { value: "Scout", label: "Scout" },
  { value: "Screenwriter", label: "Screenwriter" },
  { value: "Scribe (also Scrivener)", label: "Scribe (also Scrivener)" },
  { value: "Sculptor", label: "Sculptor" },
  { value: "Seamstress", label: "Seamstress" },
  { value: "Second mate", label: "Second mate" },
  { value: "Secret service agent", label: "Secret service agent" },
  { value: "Secret shopper", label: "Secret shopper" },
  { value: "Secretary general", label: "Secretary general" },
  { value: "Security guard", label: "Security guard" },
  { value: "Senator", label: "Senator" },
  { value: "Servant", label: "Servant" },
  {
    value: "SEO (search engine optimizer)",
    label: "SEO (search engine optimizer)",
  },
  { value: "Sexologist", label: "Sexologist" },
  { value: "Sexton", label: "Sexton" },
  { value: "Sheepshearer", label: "Sheepshearer" },
  { value: "Sheriff", label: "Sheriff" },
  { value: "Sheriff officer", label: "Sheriff officer" },
  { value: "Shepherd", label: "Shepherd" },
  { value: "Shoemaker", label: "Shoemaker" },
  { value: "Shoeshiner", label: "Shoeshiner" },
  { value: "Signalman", label: "Signalman" },
  { value: "Singer", label: "Singer" },
  { value: "Skydiver", label: "Skydiver" },
  { value: "Sleuth", label: "Sleuth" },
  { value: "Sniper", label: "Sniper" },
  { value: "Social worker", label: "Social worker" },
  { value: "Socialite", label: "Socialite" },
  { value: "Soda jerk", label: "Soda jerk" },
  { value: "Software developer", label: "Software developer" },
  { value: "Software engineer", label: "Software engineer" },
  { value: "Soil scientist", label: "Soil scientist" },
  { value: "Soldier", label: "Soldier" },
  { value: "Solicitor", label: "Solicitor" },
  { value: "Sommelier", label: "Sommelier" },
  { value: "Sonographer", label: "Sonographer" },
  { value: "Sound engineer", label: "Sound engineer" },
  { value: "Sound technicial", label: "Sound technicial" },
  { value: "Special agent", label: "Special agent" },
  { value: "Speech therapist", label: "Speech therapist" },
  { value: "Sportsman", label: "Sportsman" },
  { value: "Sports commentator", label: "Sports commentator" },
  { value: "Spy", label: "Spy" },
  { value: "Stage designer", label: "Stage designer" },
  { value: "Statistician", label: "Statistician" },
  { value: "Steersman", label: "Steersman" },
  { value: "Stevedore", label: "Stevedore" },
  { value: "Stewardess (or Steward)", label: "Stewardess (or Steward)" },
  { value: "Street artist", label: "Street artist" },
  { value: "Street musician", label: "Street musician" },
  { value: "Stock-breeder", label: "Stock-breeder" },
  { value: "Stockbroker", label: "Stockbroker" },
  { value: "Street sweeper", label: "Street sweeper" },
  { value: "Street vendor", label: "Street vendor" },
  { value: "Stripper", label: "Stripper" },
  { value: "Structural engineers", label: "Structural engineers" },
  { value: "Student", label: "Student" },
  { value: "Stunt double", label: "Stunt double" },
  { value: "Stunt performer", label: "Stunt performer" },
  { value: "Stuntman", label: "Stuntman" },
  { value: "Suicidologist", label: "Suicidologist" },
  { value: "Surgeon", label: "Surgeon" },
  { value: "Superintendent", label: "Superintendent" },
  { value: "Supervisor", label: "Supervisor" },
  { value: "Surveyor", label: "Surveyor" },
  { value: "Swimmer", label: "Swimmer" },
  { value: "Switchboard operator", label: "Switchboard operator" },
  { value: "Syndicalist", label: "Syndicalist" },
  { value: "System administrator", label: "System administrator" },
  { value: "Systems analyst", label: "Systems analyst" },
  { value: "System designer", label: "System designer" },
  { value: "Tailor", label: "Tailor" },
  { value: "Taikonaut", label: "Taikonaut" },
  { value: "Tanner", label: "Tanner" },
  {
    value: "Tapicer (also Tapestrymaker, Tapester)",
    label: "Tapicer (also Tapestrymaker, Tapester)",
  },
  { value: "Tax collector", label: "Tax collector" },
  { value: "Tax lawyer", label: "Tax lawyer" },
  { value: "Taxidermist", label: "Taxidermist" },
  {
    value: "Taxi-driver (see Cab driver)",
    label: "Taxi-driver (see Cab driver)",
  },
  { value: "Taxonomist", label: "Taxonomist" },
  { value: "Tea lady", label: "Tea lady" },
  { value: "Teacher", label: "Teacher" },
  { value: "Technical engineer", label: "Technical engineer" },
  { value: "Technician", label: "Technician" },
  { value: "Technologist", label: "Technologist" },
  { value: "Technical writer", label: "Technical writer" },
  {
    value: "Telegraphist (also Telegraph operator)",
    label: "Telegraphist (also Telegraph operator)",
  },
  { value: "Telephone operator", label: "Telephone operator" },
  { value: "Tennis player", label: "Tennis player" },
  { value: "Terminator", label: "Terminator" },
  { value: "Test developer", label: "Test developer" },
  { value: "Test pilot", label: "Test pilot" },
  { value: "Thatcher", label: "Thatcher" },
  { value: "Theatre director", label: "Theatre director" },
  { value: "Theologian", label: "Theologian" },
  { value: "Therapist", label: "Therapist" },
  { value: "Thimbler", label: "Thimbler" },
  { value: "TikToker", label: "TikToker" },
  { value: "Tiler", label: "Tiler" },
  { value: "Toolmaker", label: "Toolmaker" },
  { value: "Trader", label: "Trader" },
  { value: "Translator", label: "Translator" },
  { value: "Treasurer", label: "Treasurer" },
  { value: "Tuner", label: "Tuner" },
  { value: "Tutor", label: "Tutor" },
  { value: "Typist", label: "Typist" },
  { value: "Ufologist", label: "Ufologist" },
  { value: "Umbrella repairer", label: "Umbrella repairer" },
  { value: "Undercover agent", label: "Undercover agent" },
  { value: "Undertaker", label: "Undertaker" },
  { value: "Underwear model", label: "Underwear model" },
  { value: "Underwriter", label: "Underwriter" },
  { value: "Upholsterer", label: "Upholsterer" },
  { value: "Urban planner", label: "Urban planner" },
  { value: "Urologist", label: "Urologist" },
  { value: "Usher", label: "Usher" },
  { value: "Valet", label: "Valet" },
  { value: "Verger", label: "Verger" },
  { value: "Ventriloquist", label: "Ventriloquist" },
  { value: "Verger", label: "Verger" },
  { value: "Veterinarian", label: "Veterinarian" },
  {
    value: "Vibraphonist or Vibrafonist",
    label: "Vibraphonist or Vibrafonist",
  },
  { value: "Vicar", label: "Vicar" },
  { value: "Vice president", label: "Vice president" },
  { value: "Victualler", label: "Victualler" },
  { value: "Video editor", label: "Video editor" },
  { value: "Video game developer", label: "Video game developer" },
  { value: "Vintner", label: "Vintner" },
  { value: "Violinist", label: "Violinist" },
  { value: "Violist", label: "Violist" },
  { value: "Voice actor", label: "Voice actor" },
  { value: "Waiter (also Waitress)", label: "Waiter (also Waitress)" },
  { value: "Waiting staff", label: "Waiting staff" },
  { value: "Waste collector", label: "Waste collector" },
  { value: "Watchmaker", label: "Watchmaker" },
  { value: "Weaponsmith", label: "Weaponsmith" },
  { value: "Weatherman", label: "Weatherman" },
  { value: "Weaver", label: "Weaver" },
  { value: "Web coder", label: "Web coder" },
  { value: "Web designer", label: "Web designer" },
  { value: "Web developer", label: "Web developer" },
  { value: "Wedding planner", label: "Wedding planner" },
  { value: "Welder", label: "Welder" },
  { value: "Wet nurse", label: "Wet nurse" },
  { value: "Wine connoisseur", label: "Wine connoisseur" },
  { value: "Winemaker", label: "Winemaker" },
  { value: "Window-dresser", label: "Window-dresser" },
  { value: "Wireless operator", label: "Wireless operator" },
  { value: "Wood cutter", label: "Wood cutter" },
  { value: "Woodcarver", label: "Woodcarver" },
  { value: "Wrangler", label: "Wrangler" },
  { value: "Wrestler", label: "Wrestler" },
  { value: "Writer", label: "Writer" },
  { value: "Xylophonist", label: "Xylophonist" },
  { value: "Yodeler", label: "Yodeler" },
  { value: "YouTuber", label: "YouTuber" },
  { value: "Zookeeper", label: "Zookeeper" },
  { value: "Zoologist", label: "Zoologist" },
];
