export const HobbiesList = [
  { value: "3D printing", label: "3D printing" },
  { value: "Acroyoga", label: "Acroyoga" },
  { value: "Acting", label: "Acting" },
  { value: "Alternate history", label: "Alternate history" },
  { value: "Amateur radio", label: "Amateur radio" },
  { value: "Animation", label: "Animation" },
  { value: "Anime", label: "Anime" },
  { value: "Archery", label: "Archery" },
  { value: "Audiophilia", label: "Audiophilia" },
  { value: "Baton twirling", label: "Baton twirling" },
  { value: "Beatboxing", label: "Beatboxing" },
  { value: "Beer tasting", label: "Beer tasting" },
  { value: "Bell ringing", label: "Bell ringing" },
  { value: "Binge watching", label: "Binge watching" },
  { value: "Bird watching", label: "Bird watching" },
  { value: "Blacksmith", label: "Blacksmith" },
  { value: "Blogging", label: "Blogging" },
  { value: "Bonsai", label: "Bonsai" },
  { value: "Board/tabletop games", label: "Board/tabletop games" },
  { value: "Book discussion clubs", label: "Book discussion clubs" },
  { value: "Book restoration", label: "Book restoration" },
  { value: "Bowling", label: "Bowling" },
  { value: "Brazilian jiu-jitsu", label: "Brazilian jiu-jitsu" },
  { value: "Breadmaking", label: "Breadmaking" },
  { value: "Bullet journaling", label: "Bullet journaling" },
  { value: "Butchering", label: "Butchering" },
  { value: "Calligraphy", label: "Calligraphy" },
  { value: "Candle making", label: "Candle making" },
  { value: "Candy making", label: "Candy making" },
  { value: "Car spotting", label: "Car spotting" },
  { value: "Car fixing & building", label: "Car fixing & building" },
  { value: "Card games", label: "Card games" },
  { value: "Cardistry", label: "Cardistry" },
  { value: "Ceramics", label: "Ceramics" },
  { value: "Chatting", label: "Chatting" },
  { value: "Cheesemaking", label: "Cheesemaking" },
  { value: "Chess", label: "Chess" },
  { value: "Cleaning", label: "Cleaning" },
  { value: "Clothesmaking", label: "Clothesmaking" },
  { value: "Coffee roasting", label: "Coffee roasting" },
  { value: "Collecting", label: "Collecting" },
  { value: "Pet care", label: "Pet care" },
  { value: "Coloring", label: "Coloring" },
  { value: "Communication", label: "Communication" },
  { value: "Community activism", label: "Community activism" },
  { value: "Community radio", label: "Community radio" },
  { value: "Computer programming", label: "Computer programming" },
  { value: "Confectionery", label: "Confectionery" },
  { value: "Conlanging", label: "Conlanging" },
  { value: "Construction", label: "Construction" },
  { value: "Cooking", label: "Cooking" },
  { value: "Cosplaying", label: "Cosplaying" },
  { value: "Couponing", label: "Couponing" },
  { value: "Craft", label: "Craft" },
  { value: "Creative writing", label: "Creative writing" },
  { value: "Crocheting", label: "Crocheting" },
  { value: "Cross-stitch", label: "Cross-stitch" },
  { value: "Crossword puzzles", label: "Crossword puzzles" },
  { value: "Cryptography", label: "Cryptography" },
  { value: "Cue sports", label: "Cue sports" },
  { value: "Dance", label: "Dance" },
  { value: "Decorating", label: "Decorating" },
  { value: "Decorative birds", label: "Decorative birds" },
  { value: "Digital arts", label: "Digital arts" },
  { value: "Dining", label: "Dining" },
  { value: "Diorama", label: "Diorama" },
  { value: "Distro Hopping", label: "Distro Hopping" },
  { value: "Diving", label: "Diving" },
  { value: "Djembe", label: "Djembe" },
  { value: "DJing", label: "DJing" },
  { value: "Do it yourself", label: "Do it yourself" },
  { value: "Drama", label: "Drama" },
  { value: "Drawing", label: "Drawing" },
  { value: "Drone racing", label: "Drone racing" },
  { value: "Editing", label: "Editing" },
  { value: "Electronic games", label: "Electronic games" },
  { value: "Electronics", label: "Electronics" },
  { value: "Embroidery", label: "Embroidery" },
  { value: "Engraving", label: "Engraving" },
  { value: "Entertaining", label: "Entertaining" },
  { value: "Everyday carry", label: "Everyday carry" },
  { value: "Experimenting", label: "Experimenting" },
  { value: "Fantasy sports", label: "Fantasy sports" },
  { value: "Fashion", label: "Fashion" },
  { value: "Fashion design", label: "Fashion design" },
  { value: "Feng shui decorating", label: "Feng shui decorating" },
  { value: "Filmmaking", label: "Filmmaking" },
  { value: "Fingerpainting", label: "Fingerpainting" },
  { value: "Fishfarming", label: "Fishfarming" },
  { value: "Fishkeeping", label: "Fishkeeping" },
  { value: "Flower arranging", label: "Flower arranging" },
  { value: "Fly tying", label: "Fly tying" },
  { value: "Foreign language learning", label: "Foreign language learning" },
  { value: "Furniture building", label: "Furniture building" },
  { value: "Gambling", label: "Gambling" },
  { value: "Genealogy", label: "Genealogy" },
  { value: "Gingerbread house making", label: "Gingerbread house making" },
  { value: "Giving advice", label: "Giving advice" },
  { value: "Glassblowing", label: "Glassblowing" },
  { value: "Gardening", label: "Gardening" },
  { value: "Gongfu tea", label: "Gongfu tea" },
  { value: "Graphic design", label: "Graphic design" },
  { value: "Gunsmithing", label: "Gunsmithing" },
  { value: "Hacking", label: "Hacking" },
  { value: "Hairstyle", label: "Hairstyle" },
  { value: "Hardware", label: "Hardware" },
  { value: "Herping", label: "Herping" },
  { value: "Herp keeping", label: "Herp keeping" },
  { value: "Hobby finding", label: "Hobby finding" },
  { value: "Home improvement", label: "Home improvement" },
  { value: "Homebrewing", label: "Homebrewing" },
  { value: "Homing pigeons", label: "Homing pigeons" },
  { value: "Houseplant care", label: "Houseplant care" },
  { value: "Hula hooping", label: "Hula hooping" },
  { value: "Hydroponics", label: "Hydroponics" },
  { value: "Ice skating", label: "Ice skating" },
  { value: "Insect collecting", label: "Insect collecting" },
  { value: "Inventing", label: "Inventing" },
  { value: "Jewelry making", label: "Jewelry making" },
  { value: "Jigsaw puzzles", label: "Jigsaw puzzles" },
  { value: "Journaling", label: "Journaling" },
  { value: "Judo", label: "Judo" },
  { value: "Juggling", label: "Juggling" },
  { value: "Karaoke", label: "Karaoke" },
  { value: "Karate", label: "Karate" },
  { value: "Kendama", label: "Kendama" },
  { value: "Kitemaking", label: "Kitemaking" },
  { value: "Knife making", label: "Knife making" },
  { value: "Knitting", label: "Knitting" },
  { value: "Knot tying", label: "Knot tying" },
  { value: "Kombucha brewing", label: "Kombucha brewing" },
  { value: "Kung fu", label: "Kung fu" },
  { value: "Kun khmer", label: "Kun khmer" },
  { value: "Lace making", label: "Lace making" },
  { value: "Lapidary", label: "Lapidary" },
  { value: "Leather crafting", label: "Leather crafting" },
  { value: "Lego building", label: "Lego building" },
  { value: "Livestreaming", label: "Livestreaming" },
  { value: "Listening to music", label: "Listening to music" },
  { value: "Listening to podcasts", label: "Listening to podcasts" },
  { value: "Lock picking", label: "Lock picking" },
  { value: "Machining", label: "Machining" },
  { value: "Macrame", label: "Macrame" },
  { value: "Magic", label: "Magic" },
  { value: "Makeup", label: "Makeup" },
  { value: "Manga", label: "Manga" },
  { value: "Massaging", label: "Massaging" },
  { value: "Mazes (indoor/outdoor)", label: "Mazes (indoor/outdoor)" },
  { value: "Mechanics", label: "Mechanics" },
  { value: "Meditation", label: "Meditation" },
  { value: "Memory training", label: "Memory training" },
  { value: "Metalworking", label: "Metalworking" },
  { value: "Micropatriology", label: "Micropatriology" },
  { value: "Miniature art", label: "Miniature art" },
  { value: "Minimalism", label: "Minimalism" },
  { value: "Model building", label: "Model building" },
  { value: "Modeling", label: "Modeling" },
  { value: "Model engineering", label: "Model engineering" },
  { value: "Music", label: "Music" },
  { value: "Nail art", label: "Nail art" },
  { value: "Needlepoint", label: "Needlepoint" },
  { value: "Origami", label: "Origami" },
  { value: "Painting", label: "Painting" },
  { value: "Pen Spinning", label: "Pen Spinning" },
  { value: "Performance", label: "Performance" },
  { value: "Pet sitting", label: "Pet sitting" },
  { value: "Philately", label: "Philately" },
  { value: "Photography", label: "Photography" },
  { value: "Pilates", label: "Pilates" },
  { value: "Pipes", label: "Pipes" },
  { value: "Planning", label: "Planning" },
  { value: "Plastic art", label: "Plastic art" },
  {
    value: "Playing musical instruments",
    label: "Playing musical instruments",
  },
  { value: "Poetry", label: "Poetry" },
  { value: "Poi", label: "Poi" },
  { value: "Pole dancing", label: "Pole dancing" },
  { value: "Postcrossing", label: "Postcrossing" },
  { value: "Pottery", label: "Pottery" },
  { value: "Practical jokes", label: "Practical jokes" },
  { value: "Pressed flower craft", label: "Pressed flower craft" },
  { value: "Proofreading and editing", label: "Proofreading and editing" },
  { value: "Proverbs", label: "Proverbs" },
  { value: "Public speaking", label: "Public speaking" },
  { value: "Puppetry", label: "Puppetry" },
  { value: "Puzzles", label: "Puzzles" },
  { value: "Pyrography", label: "Pyrography" },
  { value: "Quilling", label: "Quilling" },
  { value: "Quilting", label: "Quilting" },
  { value: "Quizzes", label: "Quizzes" },
  {
    value: "Radio-controlled model playing",
    label: "Radio-controlled model playing",
  },
  { value: "Rail transport modeling", label: "Rail transport modeling" },
  { value: "Rapping", label: "Rapping" },
  { value: "Reading", label: "Reading" },
  { value: "Recipe creation", label: "Recipe creation" },
  { value: "Recreational drug use", label: "Recreational drug use" },
  { value: "Refinishing", label: "Refinishing" },
  { value: "Reiki", label: "Reiki" },
  { value: "Reviewing gadgets", label: "Reviewing gadgets" },
  { value: "Robot combat", label: "Robot combat" },
  { value: "Role-playing", label: "Role-playing" },
  { value: "Rubik's Cube", label: "Rubik's Cube" },
  { value: "Scrapbooking", label: "Scrapbooking" },
  { value: "Scuba diving", label: "Scuba diving" },
  { value: "Sculpting", label: "Sculpting" },
  { value: "Sewing", label: "Sewing" },
  { value: "Shitposting", label: "Shitposting" },
  { value: "Shoemaking", label: "Shoemaking" },
  { value: "Singing", label: "Singing" },
  { value: "Sketching", label: "Sketching" },
  { value: "Skipping rope", label: "Skipping rope" },
  { value: "Slot car", label: "Slot car" },
  { value: "Shopping", label: "Shopping" },
  { value: "Soapmaking", label: "Soapmaking" },
  { value: "Social media", label: "Social media" },
  { value: "Speedrunning", label: "Speedrunning" },
  { value: "Speculative evolution", label: "Speculative evolution" },
  { value: "Spreadsheets", label: "Spreadsheets" },
  { value: "Stamp collecting", label: "Stamp collecting" },
  { value: "Stand-up comedy", label: "Stand-up comedy" },
  { value: "Storytelling", label: "Storytelling" },
  { value: "Stretching", label: "Stretching" },
  { value: "String Figures", label: "String Figures" },
  { value: "Stripping", label: "Stripping" },
  { value: "Sudoku", label: "Sudoku" },
  { value: "Talking", label: "Talking" },
  { value: "Tabletop game", label: "Tabletop game" },
  { value: "Taekwondo", label: "Taekwondo" },
  { value: "Tanning (leather)", label: "Tanning (leather)" },
  { value: "Tapestry", label: "Tapestry" },
  { value: "Tarot", label: "Tarot" },
  { value: "Tattooing", label: "Tattooing" },
  { value: "Taxidermy", label: "Taxidermy" },
  { value: "Telling jokes", label: "Telling jokes" },
  { value: "Thrifting", label: "Thrifting" },
  { value: "Upcycling", label: "Upcycling" },
  { value: "Video editing", label: "Video editing" },
  { value: "Video game developing", label: "Video game developing" },
  { value: "Video gaming", label: "Video gaming" },
  { value: "Video making", label: "Video making" },
  { value: "VR gaming", label: "VR gaming" },
  { value: "Wargaming", label: "Wargaming" },
  { value: "Watch making", label: "Watch making" },
  { value: "Watching documentaries", label: "Watching documentaries" },
  { value: "Watching movies", label: "Watching movies" },
  { value: "Watching television", label: "Watching television" },
  { value: "Wax sealing", label: "Wax sealing" },
  { value: "Waxing", label: "Waxing" },
  { value: "Weaving", label: "Weaving" },
  { value: "Webtooning", label: "Webtooning" },
  { value: "Weight training", label: "Weight training" },
  { value: "Welding", label: "Welding" },
  { value: "Whittling", label: "Whittling" },
  { value: "Wikipedia editing", label: "Wikipedia editing" },
  {
    value: "Wikipedia racing/Wikiracing",
    label: "Wikipedia racing/Wikiracing",
  },
  { value: "Wine tasting", label: "Wine tasting" },
  { value: "Winemaking", label: "Winemaking" },
  { value: "Witchcraft", label: "Witchcraft" },
  { value: "Wood carving", label: "Wood carving" },
  { value: "Woodworking", label: "Woodworking" },
  { value: "Word searches", label: "Word searches" },
  { value: "Worldbuilding", label: "Worldbuilding" },
  { value: "Writing", label: "Writing" },
  { value: "Writing music", label: "Writing music" },
  { value: "Yarn bombing", label: "Yarn bombing" },
  { value: "Yo-yoing", label: "Yo-yoing" },
  { value: "Yoga", label: "Yoga" },
  { value: "Zumba", label: "Zumba" },
];
